version: '3.4'

services:
  caddy:
    image: caddy:2.6.4
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/root/.caddy
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local